---
- name: "Run a command"
  hosts: all
  become: true
  become_user: root
  gather_facts: yes
  tasks:

  - name: Run the scp command to copy files
    command:
      cmd: scp -p dao-rhel-nutanix:/tmp/testmotd /tmp/testmotd
