---
- name: "MOTD Copy"
  hosts: all
  become: true
  become_user: root
  gather_facts: yes
  tasks:

  - name: Copy a new motd file into place and back up the original if it differs
    copy:
      remote_src: no
      src: /tmp/testmotd
      dest: /tmp/testmotd
      owner: root
      group: root
      mode: '0644'
